In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2.0,3.3],[4,5,6.5]])
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[10,11,12],[13,14,15],[16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a3.shape

(2, 3, 3)

In [8]:
a1.ndim

1

In [9]:
a2.ndim

2

In [10]:
a3.ndim

3

In [11]:
a3.size

18

In [12]:
type(a3)

numpy.ndarray

In [13]:
a1.dtype

dtype('int32')

In [14]:
a2.dtype

dtype('float64')

In [15]:
a3.dtype

dtype('int32')

In [16]:
#Pandas based off of numpys
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2.Creating arrays

In [17]:
ones=np.ones(7)
ones

array([1., 1., 1., 1., 1., 1., 1.])

In [18]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[8, 3, 9, 6, 7],
       [4, 5, 4, 4, 0],
       [6, 5, 3, 2, 9]])

In [22]:
np.random.random((5,3))


array([[0.33474147, 0.44326844, 0.29870867],
       [0.82543355, 0.88403396, 0.96005326],
       [0.67961584, 0.24725121, 0.72033851],
       [0.01787719, 0.66198708, 0.06626929],
       [0.63827114, 0.59735592, 0.52915157]])

In [23]:
#pseudo random numbers
np.random.seed(seed=10)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9],
       [0, 8, 6],
       [4, 3, 0]])

In [24]:
np.random.seed(5)
random_array_5=np.random.random((5,3))
random_array_5

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ],
       [0.18772123, 0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987, 0.87993703]])

## 3.Viewing arrays and matrices

In [25]:
np.unique(random_array_4)

array([0, 1, 3, 4, 6, 8, 9])

In [26]:
a1

array([1, 2, 3])

In [27]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [28]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [29]:
a1[0]

1

In [30]:
a2[0]

array([1. , 2. , 3.3])

In [31]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a4=np.random.random((2,3,3,4))
a4

array([[[[0.27408646, 0.41423502, 0.29607993, 0.62878791],
         [0.57983781, 0.5999292 , 0.26581912, 0.28468588],
         [0.25358821, 0.32756395, 0.1441643 , 0.16561286]],

        [[0.96393053, 0.96022672, 0.18841466, 0.02430656],
         [0.20455555, 0.69984361, 0.77951459, 0.02293309],
         [0.57766286, 0.00164217, 0.51547261, 0.63979518]],

        [[0.9856244 , 0.2590976 , 0.80249689, 0.87048309],
         [0.92274961, 0.00221421, 0.46948837, 0.98146874],
         [0.3989448 , 0.81373248, 0.5464565 , 0.77085409]]],


       [[[0.48493107, 0.02911156, 0.08652569, 0.11145381],
         [0.25124511, 0.96491529, 0.63176605, 0.8166602 ],
         [0.566082  , 0.63535621, 0.81190239, 0.92668262]],

        [[0.91262676, 0.82481072, 0.09420273, 0.36104842],
         [0.03550903, 0.54635835, 0.79614272, 0.0511428 ],
         [0.18866774, 0.36547777, 0.24429087, 0.79508747]],

        [[0.35209494, 0.63887768, 0.49341505, 0.58349974],
         [0.93929935, 0.94354008, 0.11169243

In [33]:
a4.shape,a4.ndim

((2, 3, 3, 4), 4)

## 4. Manipulating & comparing arrays

In [34]:
a1

array([1, 2, 3])

In [35]:
ones= np.ones(3)

In [36]:
ones

array([1., 1., 1.])

In [37]:
a1+ones

array([2., 3., 4.])

In [38]:
a1-ones

array([0., 1., 2.])

In [39]:
a1*ones

array([1., 2., 3.])

In [40]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [42]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [45]:
a3.shape

(2, 3, 3)

In [46]:
a2.shape

(2, 3)

In [47]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [48]:
a2//a1 #floor division (rounds down)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [49]:
a2**2


array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [50]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [52]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [53]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [54]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])