In [43]:
import numpy as np

## DataTypes & Attributes

In [44]:
# NumPy's main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [45]:
type(a1)

numpy.ndarray

In [46]:
a2=np.array([[1,2.0,3.3],[4,5,6.5]])
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[10,11,12],[13,14,15],[16,17,18]]])

In [47]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [48]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [49]:
a3.shape

(2, 3, 3)

In [50]:
a1.ndim

1

In [51]:
a2.ndim

2

In [52]:
a3.ndim

3

In [53]:
a3.size

18

In [54]:
type(a3)

numpy.ndarray

In [55]:
a1.dtype

dtype('int32')

In [56]:
a2.dtype

dtype('float64')

In [57]:
a3.dtype

dtype('int32')

In [58]:
#Pandas based off of numpys
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2.Creating arrays

In [59]:
ones=np.ones(7)
ones

array([1., 1., 1., 1., 1., 1., 1.])

In [60]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [63]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[4, 6, 2, 9, 9],
       [9, 9, 1, 2, 7],
       [0, 5, 0, 0, 4]])

In [64]:
np.random.random((5,3))


array([[0.89241102, 0.9580135 , 0.56133712],
       [0.0905487 , 0.99598891, 0.47740172],
       [0.68491561, 0.84337526, 0.61612483],
       [0.56318751, 0.36816219, 0.6909312 ],
       [0.81616768, 0.92564349, 0.00573506]])

In [65]:
#pseudo random numbers
np.random.seed(seed=10)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9],
       [0, 8, 6],
       [4, 3, 0]])

In [66]:
np.random.seed(5)
random_array_5=np.random.random((5,3))
random_array_5

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ],
       [0.18772123, 0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987, 0.87993703]])

## 3.Viewing arrays and matrices

In [67]:
np.unique(random_array_4)

array([0, 1, 3, 4, 6, 8, 9])

In [68]:
a1

array([1, 2, 3])

In [69]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [70]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [71]:
a1[0]

1

In [72]:
a2[0]

array([1. , 2. , 3.3])

In [73]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
a4=np.random.random((2,3,3,4))
a4

array([[[[0.97173602, 0.38711375, 0.90523631, 0.50105462],
         [0.67240828, 0.88740297, 0.05838575, 0.29474664],
         [0.17769359, 0.04656562, 0.34180828, 0.91540073]],

        [[0.25271628, 0.11303782, 0.94184494, 0.49331099],
         [0.47179102, 0.68784676, 0.81708483, 0.22690731],
         [0.20235285, 0.42449878, 0.84759295, 0.9271214 ]],

        [[0.19040336, 0.68945921, 0.44586868, 0.87811028],
         [0.2956111 , 0.27020385, 0.02193189, 0.87135088],
         [0.16605978, 0.2785312 , 0.2463312 , 0.92205218]]],


       [[[0.08162816, 0.33665844, 0.68043503, 0.16556516],
         [0.5776585 , 0.42465708, 0.01314008, 0.60660289],
         [0.34691688, 0.2115269 , 0.97515003, 0.83898221]],

        [[0.44870931, 0.32124904, 0.01409788, 0.72806984],
         [0.26632355, 0.51168995, 0.62601907, 0.75290599],
         [0.15814617, 0.09131661, 0.77406715, 0.05145793]],

        [[0.40661733, 0.0360235 , 0.20778885, 0.1893977 ],
         [0.83990082, 0.74294172, 0.24467622

In [83]:
a4.shape,a4.ndim

((2, 3, 3, 4), 4)